### ISSUE TITLE
CSS 里calc() 的使用

### ISSUE THREAD

**Issue by 12Tall** [12Tall/toys#27]
## Solutions  

 - **+ 和 - 运算符的两边必须要有空白字符。** 比如，`calc(50% -8px)` 会被解析成为一个无效的表达式，解析结果是：*一个百分比 后跟一个负数长度值*。而加有空白字符的、有效的表达式 `calc(8px + -50%) `会被解析成为：*一个长度 后跟一个加号 再跟一个负百分比*。  

-  \* 和 / 这两个运算符前后不需要空白字符，但如果考虑到统一性，仍然推荐加上空白符。

- 用 0 作除数会使 HTML 解析器抛出异常。

- 涉及自动布局和固定布局的表格中的表列、表列组、表行、表行组和表单元格的宽度和高度百分比的数学表达式，auto 可视为已指定。

- `calc()` 函数支持嵌套。

参考：<https://developer.mozilla.org/zh-CN/docs/Web/CSS/calc>

下面是一个例子：
```css
* {
  margin: 0;
  padding: 0;
  width: 100%;
  height: 100%;
}

.container {
  overflow: hidden;
  text-align: left;
  --varW: '50%';

  .editor {
    display: inline-block;
    width: calc(var(--varW) - 2px);
    height: 100%;
    background-color: red;

    textarea {
      margin: 0;
      padding: 0;
      font-family: Avenir, Helvetica, Arial, sans-serif;
    }
  }

  .line {
    display: inline-block;
    width: 4px;
    height: 100%;
    background-color: white;
    cursor: ew-resize;
  }

  .pereviewer {
    vertical-align: top;
    display: inline-block;
    width: calc(100% - var(--varW) - 4px);
    height: 100%;
    background-color: green;
    overflow-y: auto;
  }
}
```
